
#ifndef TRABALHOPRATICO_POO_GAMINGPHASECOMMANDSENUM_H
#define TRABALHOPRATICO_POO_GAMINGPHASECOMMANDSENUM_H

enum GAMING_PHASE_COMMANDS {
    EXEC,
    PROX,
    COMPRAC,
    PRECOS,
    CIDADE,
    CARAVANA,
    COMPRA,
    VENDE,
    MOVE,
    AUTO,
    STOP,
    BARBARO,
    AREIA,
    MOEDAS,
    TRIPUL,
    SAVES,
    LOADS,
    LISTS,
    DELS,
    TERMINAR
};

#endif //TRABALHOPRATICO_POO_GAMINGPHASECOMMANDSENUM_H
