
#ifndef TRABALHOPRATICO_POO_CARAVANTYPEENUM_H
#define TRABALHOPRATICO_POO_CARAVANTYPEENUM_H

enum CaravanType {
    COMMERCE,
    MILITAR,
    HESTIA,
    BARBARIAN
};
#endif //TRABALHOPRATICO_POO_CARAVANTYPEENUM_H
