
#ifndef TRABALHOPRATICO_POO_CELLTYPEENUM_H
#define TRABALHOPRATICO_POO_CELLTYPEENUM_H

enum CellType {
    EMPTY,
    MOUNTAIN,
    ITEM,
    CITY,
    CARAVAN,
    BARBARIANCARAVAN,
    UNKNOWN
};

#endif //TRABALHOPRATICO_POO_CELLTYPEENUM_H
